### ISSUE TITLE
pod install报错。。。

### ISSUE THREAD

**Issue by kakashilw** [trawor/VZ#1]
pod install
Setting up CocoaPods master repo
[!] Pod::Executable pull

U   .travis.yml

A   AAActivityAction/1.0.2/AAActivityAction.podspec

A   AAShareBubbles/1.0.1/AAShareBubbles.podspec

A   AAShareBubbles/1.0.2/AAShareBubbles.podspec

A   ABContactHelper/0.1/ABContactHelper.podspec

A   ABFullScrollViewController/1.0/ABFullScrollViewController.podspec

A   ABMultiton/1.2.2/ABMultiton.podspec

A   ABMultiton/2.0.0/ABMultiton.podspec

A   ABMultiton/2.0.1/ABMultiton.podspec

A   ABMultiton/2.0.2/ABMultiton.podspec
.......

Pull is not possible because you have unmerged files.

Please, fix them up in the work tree, and then use 'git add/rm <file>'

as appropriate to mark resolution, or use 'git commit -a'.

/Library/Ruby/Gems/2.0.0/gems/claide-0.4.0/lib/claide/command.rb:217:in `rescue in run': undefined method`verbose?' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.4.0/lib/claide/command.rb:210:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.28.0/lib/cocoapods/command.rb:52:in`run'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.28.0/bin/pod:24:in `<top (required)>'
    from /usr/bin/pod:23:in`load'
    from /usr/bin/pod:23:in `<main>'

**Comment by trawor** [comment]
弄的pod有问题, 可能本地缓存被破坏了, 删除`~/.cocoapods/repos/master` 重新试试

**Comment by samniu** [comment]
是的，我也遇到了同样的问题，google了下才解决，更新一下文档吧 

rm -rf ~/.cocoapods/

**Comment by trawor** [comment]
这个跟这个项目没什么关系, 是pod本身的问题, 所以这里就不做特别说明了

**Comment by it-yang** [comment]
pod  install error

~/.cocoapods/repos/master已尝试，报同意的错误
---------------------------------------error-------------------------------------------

## Podfile

``` ruby
platform :ios, "5.0"

target 'VZ' do
    pod 'AVOSCloud', :podspec => 'https://download.avoscloud.com/sdk/iOS/current/AVOSCloud.podspec'
    pod 'AVOSCloudSNS', :podspec => 'https://download.avoscloud.com/sdk/iOS/current/AVOSCloudSNS.podspec'

    pod 'SIAlertView'
    pod 'MMDrawerController'

end
```

### Error

```
Encoding::UndefinedConversionError - "\xC2" from ASCII-8BIT to UTF-8
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:286:in `encode'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:286:in `generate'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:286:in `pretty_generate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/specification/json.rb:15:in `to_pretty_json'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/external_sources/abstract_external_source.rb:145:in `store_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/external_sources/podspec_source.rb:19:in `block (2 levels) in fetch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:153:in `open_uri'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/external_sources/podspec_source.rb:19:in `block in fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/external_sources/podspec_source.rb:11:in `fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/installer/analyzer.rb:347:in `fetch_external_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/installer/analyzer.rb:324:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/installer/analyzer.rb:323:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/installer/analyzer.rb:323:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/installer/analyzer.rb:322:in `fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/installer/analyzer.rb:57:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/installer.rb:189:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```
